CREATE TABLE Pilotos (
    IdPiloto INT NOT NULL,
    Nome VARCHAR(200) NOT NULL,
    AnoNascimento VARCHAR(10) NOT NULL, -- HEXADECIMAL VALUE
    IdPlaneta INT NOT NULL
)
GO
ALTER TABLE Pilotos ADD CONSTRAINT PK_Pilotos PRIMARY KEY (IdPiloto);
GO
ALTER TABLE Pilotos ADD CONSTRAINT FK_Pilotos_Planetas FOREIGN KEY (IdPlaneta) REFERENCES Planetas (IdPlaneta);